test again

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -13,8 +13,10 @@ env:
   DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
   REPO_DIRECTORY: ${{ vars.REPO_DIRECTORY }}
   CLUSTER_ID: ${{ vars.CLUSTER_ID }}
-  TEST_DLT_PIPELINE_ID: 280456420773804 
-  TEST_DLT_PIPELINE_NAME: "Demo 02 Tests"
+  TEST_PIPELINE_ID: 280456420773804 
+  TEST_PIPELINE_NAME: "Demo 02 Tests"
+  DLT_PIPELINE_ID: cccbee24-a93b-4934-b588-751e1eee0981
+  DLT_PIPELINE_NAME: "Demo 02 Integaration Test"
 
 permissions:
   checks: write
@@ -50,7 +52,7 @@ jobs:
         databricks -v
         DLT_START=$SECONDS
         DLT_START_ISO=$(date --iso-8601=seconds)
-        JOB_ID=$(databricks jobs run-now ${{ env.TEST_DLT_PIPELINE_ID }} --no-wait | jq .run_id)
+        JOB_ID=$(databricks jobs run-now ${{ env.TEST_PIPELINE_ID }} --no-wait | jq .run_id)
         sleep 15
         while true; do
           DLT_STATUS=$(databricks jobs get-run $JOB_ID |jq -r .state.life_cycle_state)
@@ -66,7 +68,7 @@ jobs:
         DLT_ERRORS=$(( "$DLT_RESULT" = "FAILED" ? 1 : 0 ))
         DLT_SKIPPED=$(( "$DLT_RESULT" = "CANCELED" ? 1 : 0 ))
         echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"DLT Integration test\" tests=\"1\" skipped=\"$DLT_SKIPPED\" errors=\"$DLT_ERRORS\" failures=\"$DLT_ERRORS\" time=\"$((DLT_FINISH-DLT_START))\" timestamp=\"${DLT_START_ISO}\">" > test-dlt.xml
-        echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.TEST_DLT_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
+        echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.TEST_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
         if [ "$DLT_RESULT" = "FAILED" ]; then
           echo "<failure message=\"DLT test failure\">Pipeline update with ID ${JOB_ID} has failed</failure>" >> test-dlt.xml
         elif [ "$DLT_RESULT" = "SKIPPED" ]; then
@@ -96,40 +98,25 @@ jobs:
       with:
         python-version: 3.8
 
-    - name: Install libraries
-      run: |
-        pip install --upgrade pip nutter
-        curl -sSL https://install.python-poetry.org | python -
-        export PATH=$PATH:$HOME/.poetry/bin
-        poetry install --no-root
-        
     - name: install-databricks-cli
       uses: microsoft/install-databricks-cli@v1.0.0
-
+      
     - name: Update databricks repo
       run: |
         databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"
-
-    - name: Run Local Tests
-      run: |
-        poetry run pytest tests/unit-local --junit-xml=test-local.xml --cov
-
-    - name: Run Notebook Tests
-      run: |
-        nutter run "$REPO_DIRECTORY/tests/unit-notebooks/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
 
     - name: Install Databricks cli v2
       run: |
         pip uninstall databricks-cli -y
         sleep 10
-        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh    
-
-    - name: Run Integration test Pipeline
+        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  
+         
+    - name: Run Unit Tests
       run: |
         databricks -v
         DLT_START=$SECONDS
         DLT_START_ISO=$(date --iso-8601=seconds)
-        JOB_ID=$(databricks jobs run-now ${{ env.TEST_DLT_PIPELINE_ID }} --no-wait | jq .run_id)
+        JOB_ID=$(databricks jobs run-now ${{ env.TEST_PIPELINE_ID }} --no-wait | jq .run_id)
         sleep 15
         while true; do
           DLT_STATUS=$(databricks jobs get-run $JOB_ID |jq -r .state.life_cycle_state)
@@ -145,7 +132,7 @@ jobs:
         DLT_ERRORS=$(( "$DLT_RESULT" = "FAILED" ? 1 : 0 ))
         DLT_SKIPPED=$(( "$DLT_RESULT" = "CANCELED" ? 1 : 0 ))
         echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"DLT Integration test\" tests=\"1\" skipped=\"$DLT_SKIPPED\" errors=\"$DLT_ERRORS\" failures=\"$DLT_ERRORS\" time=\"$((DLT_FINISH-DLT_START))\" timestamp=\"${DLT_START_ISO}\">" > test-dlt.xml
-        echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.TEST_DLT_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
+        echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.TEST_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
         if [ "$DLT_RESULT" = "FAILED" ]; then
           echo "<failure message=\"DLT test failure\">Pipeline update with ID ${JOB_ID} has failed</failure>" >> test-dlt.xml
         elif [ "$DLT_RESULT" = "SKIPPED" ]; then
@@ -155,12 +142,50 @@ jobs:
         if [ "$DLT_RESULT" != "SUCCESS" ]; then
           exit 1
         fi
-    
+
     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3
       if: success() || failure() # always run even if the previous step fails
       with:
-        report_paths: '**/test-*.xml'  
+        report_paths: '**/test-*.xml'
+
+    - name: Run Integration Test
+      run: |
+        databricks -v
+        DLT_START=$SECONDS
+        DLT_START_ISO=$(date --iso-8601=seconds)
+        JOB_ID=$(databricks jobs run-now ${{ env.DLT_PIPELINE_ID }} --no-wait | jq .run_id)
+        sleep 15
+        while true; do
+          DLT_STATUS=$(databricks jobs get-run $JOB_ID |jq -r .state.life_cycle_state)
+          DLT_RESULT=$(databricks jobs get-run $JOB_ID |jq -r .state.result_state)
+          if [ "$DLT_STATUS" = "CANCELED" -o "$DLT_STATUS" = "SKIPPED" -o "$DLT_STATUS" = "FAILED" -o "$DLT_STATUS" = "TERMINATED" ]; then
+            echo "Exiting loop with status '$DLT_STATUS' with results '$DLT_RESULT'"
+            break
+          fi
+          echo "DLT pipeline status is '$DLT_STATUS'. Waiting..."
+          sleep 15
+        done
+        DLT_FINISH=$SECONDS
+        DLT_ERRORS=$(( "$DLT_RESULT" = "FAILED" ? 1 : 0 ))
+        DLT_SKIPPED=$(( "$DLT_RESULT" = "CANCELED" ? 1 : 0 ))
+        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"DLT Integration test\" tests=\"1\" skipped=\"$DLT_SKIPPED\" errors=\"$DLT_ERRORS\" failures=\"$DLT_ERRORS\" time=\"$((DLT_FINISH-DLT_START))\" timestamp=\"${DLT_START_ISO}\">" > test-dlt.xml
+        echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.DLT_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
+        if [ "$DLT_RESULT" = "FAILED" ]; then
+          echo "<failure message=\"DLT test failure\">Pipeline update with ID ${JOB_ID} has failed</failure>" >> test-dlt.xml
+        elif [ "$DLT_RESULT" = "SKIPPED" ]; then
+          echo '<skipped />' >> test-dlt.xml
+        fi
+        echo '</testcase></testsuite></testsuites>' >> test-dlt.xml
+        if [ "$DLT_RESULT" != "SUCCESS" ]; then
+          exit 1
+        fi
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/test-*.xml' 
         
   DeployProduction:
     environment: prod
