b

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -76,20 +76,12 @@ jobs:
         if [ "$DLT_RESULT" != "SUCCESS" ]; then
           exit 1
         fi
-    
-    #- name: Run Local Tests
-    #  run: |
-    #    poetry run pytest tests/unit-local --junit-xml=test-local.xml --cov
 
-    #- name: Run Notebook Tests
-    #  run: |
-    #    nutter run "$REPO_DIRECTORY/tests/unit-notebooks/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
-
-    #- name: Publish Test Report
-    #  uses: mikepenz/action-junit-report@v3
-    #  if: success() || failure() # always run even if the previous step fails
-    #  with:
-    #    report_paths: '**/test-*.xml'
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/test-*.xml'  
      
   OnRelease:
     if: startsWith(github.ref_name, 'releases')
